/**
 * generated by Xtext 2.10.0
 */
package org.aiotml.xtext.ui;

import org.aiotml.xtext.ui.AbstractAiotMLUiModule;
import org.aiotml.xtext.ui.AiotMLAntlrTokenToAttributeIdMapper;
import org.aiotml.xtext.ui.AiotMLHighlightingConfiguration;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AiotMLUiModule extends AbstractAiotMLUiModule {
  public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
    return AiotMLAntlrTokenToAttributeIdMapper.class;
  }
  
  public Class<? extends DefaultHighlightingConfiguration> bindDefaultHighlightingConfiguration() {
    return AiotMLHighlightingConfiguration.class;
  }
  
  public AiotMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
