/**
 * generated by Xtext 2.10.0
 */
package org.aiotml.xtext.validation;

import org.aiotml.xtext.aiotML.AiotMLPackage;
import org.aiotml.xtext.aiotML.Thing;
import org.aiotml.xtext.constraints.AiotMLHelpers;
import org.aiotml.xtext.helpers.IncludeCycle;
import org.aiotml.xtext.helpers.ThingHelper;
import org.aiotml.xtext.validation.AbstractAiotMLValidator;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.Exceptions;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AiotMLValidator extends AbstractAiotMLValidator {
  @Check
  public void checkNoCyclesInThingIncludes(final Thing thing) {
    try {
      ThingHelper.allIncludedThingsWithCheck(thing);
      AiotMLHelpers.allThingFragmentsWithCheck(thing);
    } catch (final Throwable _t) {
      if (_t instanceof IncludeCycle) {
        final IncludeCycle e = (IncludeCycle)_t;
        this.error(e.getMessage(), thing, AiotMLPackage.eINSTANCE.getThing_Includes());
        return;
      } else {
        throw Exceptions.sneakyThrow(_t);
      }
    }
  }
}
