/**
 * generated by Xtext 2.10.0
 */
package org.aiotml.xtext.tests;

import com.google.inject.Inject;
import org.aiotml.xtext.aiotML.AiotMLModel;
import org.aiotml.xtext.tests.AiotMLInjectorProvider;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(AiotMLInjectorProvider.class)
@SuppressWarnings("all")
public class AiotMLParsingTest {
  @Inject
  private ParseHelper<AiotMLModel> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("thing Xtext{}");
      _builder.newLine();
      final AiotMLModel result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
