/**
 * generated by Xtext 2.10.0
 */
package org.aiotml.xtext.web;

import org.aiotml.xtext.web.AbstractAiotMLWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AiotMLWebModule extends AbstractAiotMLWebModule {
}
