/**
 * generated by Xtext 2.10.0
 */
package org.aiotml.xtext;

import org.aiotml.xtext.AiotMLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AiotMLStandaloneSetup extends AiotMLStandaloneSetupGenerated {
  public static void doSetup() {
    new AiotMLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
