/**
 * generated by Xtext 2.10.0
 */
package org.aiotml.xtext;

import org.aiotml.xtext.AbstractAiotMLRuntimeModule;
import org.aiotml.xtext.AiotMLTerminalConverter;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AiotMLRuntimeModule extends AbstractAiotMLRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return AiotMLTerminalConverter.class;
  }
}
