@startuml
skinparam defaultTextAlignment left
caption Behavior of thing WheelControl
[*] --> default
state default{
state Stopped{
	Stopped : entry / ...\n

Stopped --> Forward : e:ctrl?forward\naction ...\n

Stopped --> Backward : e:ctrl?backward\naction ...\n
}
state Forward{

Forward --> Forward : e:ctrl?forward\naction ...\n

Forward --> Stopped : e:ctrl?stop
}
state Backward{

Backward --> Backward : e:ctrl?backward\naction ...\n

Backward --> Stopped : e:ctrl?stop
}
[*] --> Stopped
	default : entry / ...\n
}
@enduml
